---
language: ruby
rvm:
  - 2.1.5
  - 1.9.3-p551
before_script: "if [[ $TRAVIS_RUBY_VERSION != '1.9.3-p551' || $TRAVIS_SECURE_ENV_VARS != 'true' ]]; then unset CODECLIMATE_REPO_TOKEN; fi"
notifications:
  webhooks:
    urls:
      - http://build-monitor.cfapps.io/projects/JBP/webhook
    on_start: true
env:
  global:
    secure: chtqT1mTsdgd7WFeieNcMnwK4bI+4kzpNbzHo18ITOEsjrTxHinYGRitS+CbJ0sVivOlfunWkF2mcEs1941LCSGsUzNVv8tEYfAS94HO/dK/WJMEtpH8r1JTXoP4yY2rb86ynSB79LuIzjBHpEv4FohrxdScLaoy88+Aw3boauM= #CODECLIMATE_REPO_TOKEN
