# TODO License.

# Configuration for the JAVA LSP server component
---
version: 0.0.+
repository_root: "https://buildpackcomponentrepositorycdx.cfapps.sap.hana.ondemand.com"
env:
    workdir: language_server_node_cdx/
    exec: language_server_node_cdx/launcher.sh
    ipc:
        protocol: "socket-client"
        clientport: 8765
